"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_by     = "natural"
linemode    = "size"

[opener]
play =  [
    { run = 'iina --no-stdin "$@"' }
]

[tasks]
image_bound = [10000,10000]
